services:
  files:
    build:
      context: .
      dockerfile: Dockerfile
    # Ensure config files and shares are mounted so data persists
    volumes:
      - ./config.toml:/app/config.toml:ro
      - ./shares:/shares
      # Not essential, for extra themes, images, scripts, etc.
      - ./static/extra:/app/static/extra:ro
    # Expose the service on port 8000 on the host
    # In production this should be put behind a reverse proxy supporting TLS
    ports:
      - 8000:8000
